name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt update
    - run: sudo apt install --only-upgrade gcc
    - run: gcc --version
    - uses: actions/checkout@v4
    - name: Run all tests
      run: make test
