name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1.3
    - uses: actions/checkout@v4
    - name: make test
      run: make test
